filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

setup.template:
  name: "docker"
  pattern: "docker-*"

setup.ilm.enabled: false

output.logstash:
  hosts: ["127.0.0.1:5044"]
  index: "docker"

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true
      